name: el-bot
qq: 996955042

# url_text{url}:    直接读取url返回的字串
# url_img{url}:     返回url指向的图片
# at:               sender表示消息的发送者；all表示全体成员；如果都不是则后跟的数字代表QQ号
# $n:               利用py正则自带的分组功能实现简单的变量使用功能，$n代表正则表达式中说明的第n-1组
# var{$n}:          直接回复正则所匹配到的某个组

group:
  watch:
    # 从url读取文本发送并@全体成员
    - text: say
      response: url_text{https://xxxx}
      at: all
    - text: 说话
      response: text{https://xxxx}
      at: all
    - text: 发言
      response: json{https://xxxx}
      json: message
      at: none

    - keyword: sdl
      response: url_img{https://xxxx.jpg}
      at: none
    - keyword: 是大佬
      response: local_img{/usr/image/dalao.jpg}
      at: none

    # 消息：say demo；回复：@发送者 demo
    # 括号内的正则会被自动分组，$0则代表第零组
    - regxp: say(?:\s)(.*)
      response: var{$0}
      at: sender

    # 满足任意一个即可
    - text:
        - 你好
        - hello
      response: text{你好啊}
      at: sender

    # 自带禁言功能，当群管理名额不够的时候。
    - text: lock
      sender: 具有权限的QQ号
      operator:
        - ban_all
      response: text{开启全员禁言}
    # 禁言指定QQ号
    - text: lock(?:\s)([0-9]+)
      sender: 具有权限的QQ号
      operator:
        - ban(15s){$0}
      response: text{恭喜$0喜提禁言套餐}
